@startuml

note "Part of JavaFx" as N1
N1 .. Canvas
N1 .. GraphicsContext

class GraphicsContext {
strokeLine()
}

class Canvas

class ResizableCanvas extends Canvas{
+GraphicsContext gc
}

interface KJDigitalSignalProcessor

abstract class VisualizerModel extends ResizableCanvas implements KJDigitalSignalProcessor

class VisualizerDrawer extends VisualizerModel {
drawOscilloScopeLines()
drawOscilloscope(boolean stereo)
}

abstract class Visualizer extends VisualizerDrawer {
}

class XPlayerVisualizer extends Visualizer

class MicrophoneVisualizer extends Visualizer

class PaintService extends AnimationTimer {
handle()
}

class Oscilloscope {
visualizerDrawer
}

Oscilloscope o-- VisualizerDrawer : has a reference to
VisualizerDrawer o-- Oscilloscope : Creates Oscilloscope and has a reference to it
ResizableCanvas o-- GraphicsContext

@enduml